version: "3.8"

services:
  myapp:
    build: myapp/
    container_name: myapp
    command: sh ./docker-entrypoint.sh
    ports:
      - $MYAPP_PORT:$MYAPP_PORT
      - $DEBUG_MODE_PORT:$DEBUG_MODE_PORT
    environment:
      - PORT=$MYAPP_PORT
      - SERVICE_NAME=myapp
      - DEBUG_MODE=$DEBUG_MODE
      - DEBUG_MODE_PORT=$DEBUG_MODE_PORT